sudo: required
dist: trusty
language: csharp

# Add build number to version
before_script: sed -ri "s/Version\(\"(.*).0.0\"\)/Version(\"\1.${TRAVIS_BUILD_NUMBER}.0\")/g" OxidePatcher/Properties/AssemblyInfo.cs

# Build the project
solution: OxidePatcher.sln /p:win32Icon="Resources/logo.ico"

# Run deployment script
after_success: "[[ $TRAVIS_REPO_SLUG == OxideMod/OxidePatcher ]] && [[ $TRAVIS_PULL_REQUEST == false ]] && [[ $TRAVIS_BRANCH == master ]] && ./deploy.sh"

notifications:
  email: false
  slack:
    rooms:
      secure: "dljLAegQpS8d9cHCz0YYtjoL1e1UauNlnp1d3qqrb1uuQzwRAcdvhdzp8Nz/qNjWg8DWEF6rZwpP1TNSiWIrBiefEjW/VQNGfn3SAyx2oE6GCDk8OHZoUuN9vCekVfFfzLXiXy+SD6dQSRdA7RtqQwiRep5vf4auatxWdBb7G9k="

env:
  global:
    - secure: "VfJq/lzfekhZ4+gcHig92C2HFXa+0FgQHjTr8GgUHiIkzKp0X6jy+3J6yfTu60ova2zmZkkT8EWW0HTQk4+0zkq2Rk63BJX1yuCUgABwTV1fNmebREp4OQ6GDMMxudmMjgcg+cvO4SokshPtqLPnOeyzSoCfF86G6RVf+UZ6CLM="
