language: csharp

# Add build number to version
before_script:
  - sed -ri "s/Version\(\"(.*).0.0\"\)/Version(\"\1.${TRAVIS_BUILD_NUMBER}.0\")/g" OxidePatcher/Properties/AssemblyInfo.cs

# Build the project
solution: OxidePatcher.sln /p:Configuration=Release

# Perform after compilation/test success
after_success:
  # Set execute permissions and run deployment script
  - "[[ $TRAVIS_PULL_REQUEST == false ]] && [[ $TRAVIS_REPO_SLUG == OxideMod/Oxide-Patcher ]] && [[ $TRAVIS_BRANCH == master ]] && ./deploy.sh"

# Notification services
notifications:
  # Disable build status email notifications, until the issue with forks is fixed
  email: false
  # IRC notification
  irc: "chat.freenode.net#oxidemod"

# Environmental system variables
env:
  global:
    # Super secure, encrypted variables! Ssssh!
    - secure: "ilEpgbozLNS/FXqlW4NXOTd8cCh3EVzfh/b89VDLGGF3N3Lpt+nDBtC4PZj1+0eNNMX946dFMEMXgm2DfD8G9TqAEaBA2e7Ekf0jMwNWER94G7/TqQTpfXgbmjAO2TvY0sZc0Ek/3i1I9yBzU9WtgQOpFYtCrB21FCxarHxzolU="
