# Source language (using C since .NET and C# are not supported yet)
language: c

# Install dependencies needed to compile .NET and C#
before_script:
  - curl http://download.mono-project.com/repo/xamarin.gpg | sudo apt-key add -
  - echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee -a /etc/apt/sources.list
  - echo "deb http://download.mono-project.com/repo/debian wheezy-libtiff-compat main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install mono-devel mono-dmcs mono-gmcs
  - sed -ri "s/Version\(\"(.*).0.0\"\)/Version(\"\1.${TRAVIS_BUILD_NUMBER}.0\")/g" OxidePatcher/Properties/AssemblyInfo.cs

# Run the XBuild project file
script: xbuild OxidePatcher.sln /p:Configuration=Release

# Perform after compilation/test success
after_success:
  # Set execute permissions and run deployment script
  - "[[ $TRAVIS_PULL_REQUEST == false ]] && [[ $TRAVIS_REPO_SLUG == OxideMod/Oxide-Patcher ]] && [[ $TRAVIS_BRANCH == master ]] && ./deploy.sh"

# Notification services
notifications:
  # Disable build status email notifications, until the issue with forks is fixed
  email: false
  # IRC notification
  irc: "chat.freenode.net#oxidemod"

# Environmental system variables
env:
  global:
    # Super secure, encrypted variables! Ssssh!
    - secure: "Gt1IPaWEM+3MjKp+7uXJTwRsjyHCn/SWyAYwlBojUiPystPFEEWLv0/rDr75FKKt+tWH6L3evBGH47HaKp4TSgrK+sJ/Pr2obDfnVYQ/ZETdcg/d/n1XoCVXQ8hcUQjNPqbW/UWxDMdL/p8M65i063IsvmMuaaagyeiZ1uwJjPM="
