sudo: required
dist: trusty
language: csharp

# Add build number to version
before_script: sed -ri "s/Version\(\"(.*).0.0\"\)/Version(\"\1.${TRAVIS_BUILD_NUMBER}.0\")/g" OxidePatcher/Properties/AssemblyInfo.cs

# Build the project
solution: OxidePatcher.sln /p:win32Icon="Resources/logo.ico"

# Run deployment script
after_success: "[[ $TRAVIS_REPO_SLUG == OxideMod/OxidePatcher ]] && [[ $TRAVIS_PULL_REQUEST == false ]] && [[ $TRAVIS_BRANCH == master ]] && ./deploy.sh"

notifications:
  email: false
  slack:
    rooms:
      secure: "dljLAegQpS8d9cHCz0YYtjoL1e1UauNlnp1d3qqrb1uuQzwRAcdvhdzp8Nz/qNjWg8DWEF6rZwpP1TNSiWIrBiefEjW/VQNGfn3SAyx2oE6GCDk8OHZoUuN9vCekVfFfzLXiXy+SD6dQSRdA7RtqQwiRep5vf4auatxWdBb7G9k="

env:
  global:
    - secure: "Hx8xFKENnlY33pOx7NJR50/mRNPYBzl7FJbfJIckaJ46d76XH/I+hfzlMJvX3nv146Nxp8H7tQYEAvyEX8cMLNyShT/fIfk0a77Ufi6f4Y5JmpvmNTuasAyoW8BrQc2CYB65meDgdKD5PD1zW7VkMzvQ8rAdmVNbwF4jQaqUtnk="
