# Source language (using C since .NET and C# are not supported yet)
language: c

# Install dependencies needed to compile .NET and C#
before_script:
  - curl http://download.mono-project.com/repo/xamarin.gpg | sudo apt-key add -
  - echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee -a /etc/apt/sources.list
  - echo "deb http://download.mono-project.com/repo/debian wheezy-libtiff-compat main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install mono-devel mono-dmcs mono-gmcs
  - sed -ri "s/Version\((.*).0\)/Version(\"\1.$TRAVIS_BUILD_NUMBER\")/g" $TRAVIS_BUILD_DIR/OxidePatcher/Properties/AssemblyInfo.cs

# Run the XBuild project file
script: xbuild Oxide2Patcher.sln /p:Configuration=Release

# Perform after compilation/test success
after_success:
  # Set execute permissions and run deployment script
  - "[[ $TRAVIS_PULL_REQUEST == false ]] && [[ $TRAVIS_REPO_SLUG == RustOxide/Oxide-2-Patcher ]] && [[ $TRAVIS_BRANCH == master ]] && ./deploy.sh"

# Notification services
notifications:
  # Disable build status email notifications, until the issue with forks is fixed
  email: false
  # IRC notification
  irc: "chat.freenode.net#rustoxide"

# Environmental system variables
env:
  global:
    # Super secure, encrypted variables! Ssssh!
    - secure: "ipV8ssLmSP28fiObYj/p7sQcoGRiLCTTRy6EIMXmO7fBlqVMrZ04+/lCXE/TcLGAgc7yrRwhxolxQs8x0e4+mpN9rtQN0ox9QpP3woEMCNRwqQ8ZQjlyea9Jijf5FgLqNFrSjyBmmsB4dsdy5muYqwZnSSbLXaRjXhstv9Fq5Sc="
