language: csharp

# Add build number to version
before_script: sed -ri "s/Version\(\"(.*).0.0\"\)/Version(\"\1.${TRAVIS_BUILD_NUMBER}.0\")/g" OxidePatcher/Properties/AssemblyInfo.cs

# Build the project
solution: OxidePatcher.sln

# Run deployment script
after_success: "[[ $TRAVIS_PULL_REQUEST == false ]] && [[ $TRAVIS_REPO_SLUG == OxideMod/OxidePatcher ]] && [[ $TRAVIS_BRANCH == master ]] && ./deploy.sh"

notifications:
  # Disable build status email notifications, until the issue with forks is fixed
  email: false
  # IRC notification
  irc: "chat.freenode.net#oxidemod"

# Environmental system variables
env:
  global:
    # Super secure, encrypted variables! Ssssh!
    - secure: "AeDGzUJownb0BqhaEZ+p6kZK8iZI6v1XE0rgulgYWOJ5mzji8sSJuVjW14WOPnUAVSlWUfXe814nBRXjHiV1qsN9UPuvgMf2Ze56vtV0FlvJ+ykfuI8mXGilAex7qhnNLTzbrzJLs5Q943ljPC2djVYqtrcFpm3kHDJfZahQ0B8="
